### ISSUE TITLE
Bugs pada fungsi deleteNoteById pada class NotesService

### ISSUE THREAD

**Issue by fhyfr** [dicodingacademy/a271-backend-menengah-labs#1]
Sepertinya saya menemukan ada bugs pada kode berikut:

![bugs](https://user-images.githubusercontent.com/51892934/121655476-d8881900-cac8-11eb-89c1-98ec272a0b45.png)

Jika kita menghapus satu row di database dan masih tersisa beberapa row maka fungsi ini akan selalu mengembalikan nilai error. Karena untuk logika !result.rows.length = yang berarti apabila data/ record yang dikembalikan kosong.

Mohon koreksinya.

**Comment by dimasmds** [comment]
Maaf saya kurang paham maksdnya. Jika catatan id yang diharapkan tidak ditemukan, memang kondisi yang diharapkan adalah eror NotFound kan?

**Comment by fhyfr** [comment]
Betul mas hasilnya error NotFound tapi jika logika programnya if(!result.rows.length) kode dalam logika akan selalu dieksekusi apabila jumlah record di database lebih dari satu/ ada banyak data. 
Boleh dicoba dulu mas dengan banyak record di database dan coba hapus satu data apakah errornya akan tetap jalan atau tidak.

**Comment by dimasmds** [comment]
Maaf delay response mas. Tapi penjelasannya masih belum masuk.

Apa relevansinya `result.rows.length` dengan banyak data di database? Bukannya result.rows hanya mengembalikan data yang terhapus dari database? Karena kan di sana querynya: `DELETE FROM notes WHERE id = {id} RETURNING id`.

Jadi kalo misalkan ada banyak di database, namun id catatan yang hendak dihapus tidak ditemukan, result.rows.length akan bernilai 0. Dan `if(!result.rows.length)` akan menhasilkan `true` (karena `0` adalah falsy), dan `throw NotFoundError` karena tidak ada data yang dihapus.
